### ISSUE TITLE
[Major] User profile, image import and search engine issues

### ISSUE THREAD

**Issue by janejuan** [Info442-team-2/friendly-mvp#30]
-	Major: The result did not align what users selected. The application provides only baljeet fan club and Washington Huskies. 
-	Major: The user profile did not have any content even after users already filled in the form in the previous page. The contents were all blank. 
-	Major: The user profile did not update even though users added new contents on the profile page. 
-	Major: The image URL cannot be loaded which affected the function to create new groups.
-	Major: When the search engine provided no result, it showed blank instead of any error message.

**Comment by KeithSRoberts** [comment]
Can you clarify the steps to reproduce these bugs? Perhaps screenshots? Browser? What machine are you on? A couple of these sound like assumptions about the apps behavior, it would help a lot if you could add more details for these bugs so we can observe them. Thank you

**Comment by lockheedmartian** [comment]
1. I imagine that when you encountered this, there were only 2 groups and that is why you saw them (we don't match groups with your interests if they don't exist)
2. Most likely you did not follow instructions which is why your user profile settings did not appear on your account. I have to assume this since you didn't follow instructions on the canvas HW7 assignment either and provide use reproduction steps. 
3. Again, you probably didn't click the "Save Changes" button on the user account. This button must be pressed to ensure the user doesn't change important information (such as password) accidentally. Although since you never provide reproduction details, it is hard to know for certain if you did or did not save changes.
4. Your image URL was probably bad. Throwing an error when a user inputs an invalid URL is by design. Again you should have provided the image URL for us to reproduce this issue.
5. Noted this is a valid concern (although its a duplicate).

6. None of these are major bugs, please be more reserved when you use this label in the future.
