### ISSUE TITLE
Dashboard disappears

### ISSUE THREAD

**Issue by amoghdave** [Info442-team-2/friendly-mvp#31]
**Describe the bug**
The dashboard doesn't display user's groups after searching for a group

**To Reproduce**
1. Log In
2. Search for a group ie. "Kiki" (a group that doesn't exist)
3.  click on My Profile
4.  click back onto dashboard 

**Expected behavior**
dashboard should have refreshed and should show user's original groups that are subscribed to, but it has actually saved the search "Kiki" and shows no results
 - maybe add a notification that says "no groups with that keyword exist"

**Screenshots**
<img width="1680" alt="Screen Shot 2019-12-05 at 4 36 23 PM" src="https://user-images.githubusercontent.com/3924743/70285731-61f4b780-177d-11ea-952e-5bf95304e648.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari & Chrome

**Additional context**
there should be a response from the browser that shows that no groups exist with those keywords entered into the search

**Comment by KeithSRoberts** [comment]
It seems that the dashboard is still rendering, you just dont have any results in the dashboard due to searching for "kiki" which does not match any groups. Though this is still confusing, so we are going to add a message that is displayed whenever you dont have results on the dash. On top of this, we will clear your previous search when you navigate back to the dash so that users wont be confused.

**Comment by KeithSRoberts** [comment]
Fixed by https://github.com/Info442-team-2/friendly-mvp/commit/1f01bd7022c45f42238097e4991a1f900359de8d
