### ISSUE TITLE
App logs user out on refresh

### ISSUE THREAD

**Issue by tfpenner** [Info442-team-2/friendly-mvp#34]
**Describe the bug**
When refreshing the page, I am redirected to the login page.

**To Reproduce**
1. Click refresh button in browser

**Expected behavior**
Refreshes current page, possibly loading new information

**Desktop (please complete the following information):**
Chrome

**Comment by KeithSRoberts** [comment]
This is intended, since we are not storing entire user sessions (this was decided by design because this would add a lot of complexity to our MVP) the current user is only maintained if you navigate throughout the site, as soon as you refresh/navigate away the current user must be reprovided by logging in.
