### ISSUE TITLE
Major - Display is not responsive

### ISSUE THREAD

**Issue by chencal-1622780** [Info442-team-2/friendly-mvp#55]
**Describe the bug**
After logging from the log-in/sign up page and after going through the activities section, the dashboard and the other pages seems to display component overlap(its hard to describe but here's a picture attached)

**To Reproduce**
1. Go to to the website
2. Fill in user information
3. Click sign-up
4. Click on any interest and click next:social links
5. Click Finish sign up

**Expected behavior**
Expected behavior would be to successfully render the website in a responsive manner

**Screenshots**
<img width="1419" alt="Screen Shot 2019-12-09 at 5 41 03 AM" src="https://user-images.githubusercontent.com/26780640/70440396-f6456f80-1a46-11ea-8253-922b70f9cdbb.png">

<img width="808" alt="Screen Shot 2019-12-09 at 5 48 51 AM" src="https://user-images.githubusercontent.com/26780640/70440705-a1562900-1a47-11ea-8845-32e3f00509b3.png">

**Laptop (please complete the following information):**
 - OS:MacOs [e.g. iOS]
 - Browser: Safari
 - Version 14.0

**Additional context**
Users cannot read the information being displayed on the dashboard and the other pages

**Comment by chencal-1622780** [comment]
Reproduce the bug multiple times and still did the same thing.

**Comment by KeithSRoberts** [comment]
After doing some research it appears that our layout is breaking specifically on Safari (Versions <10) due to incompatibility issues with flexbox, a CSS3 technology. Safari requires your css to be annotated with vendor-prefixes in order for it to read correctly, on top of this some flex properties simply are not supported like they are in other browsers. Unfortunately, we designed our website entirely with flexbox, so this layout-breaking issue spans all of our pages/components. To fix this, we would need to either entirely rewrite our css without flexbox or rewrite our entire css again but with vendor prefixes. Im going to go ahead and mark this as wontfix for the time being as it seems it requires a massive restructuring of all of our css code for all of our components. To see more about the incompatibilities with flexbox and Safari, see: https://stackoverflow.com/questions/35137085/flexbox-code-working-on-all-browsers-except-safari-why
